variables:
  PROJECT_NAME: gitlab-runner 测试

before_script:
  - echo before_script

stages:
  # - test
  - build

build:
  stage: build
  script:
    - echo 开始build
    - git --version
    - git remote remove origin
    - git remote add origin git@github.com:rookiewp/wp.git
    - git status
    - git log
    - git push -u origin master
  tags:
    - build
  # 只打包dev分支
  only:
    - branches
